spring:
  profiles:
    active: @activeProfile@ #根據mvn clean package -P <profile-id>，來決定這個參數的值。詳細可以看pom檔的profiles標籤的設置。

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
